package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public M setBlogId(java.lang.Integer blogId) {
		set("blogId", blogId);
		return (M)this;
	}

	public java.lang.Integer getBlogId() {
		return get("blogId");
	}

	public M setBlogText(java.lang.String blogText) {
		set("blogText", blogText);
		return (M)this;
	}

	public java.lang.String getBlogText() {
		return get("blogText");
	}

	public M setCreDate(java.util.Date creDate) {
		set("creDate", creDate);
		return (M)this;
	}

	public java.util.Date getCreDate() {
		return get("creDate");
	}

	public M setBlogTitle(java.lang.String blogTitle) {
		set("blogTitle", blogTitle);
		return (M)this;
	}

	public java.lang.String getBlogTitle() {
		return get("blogTitle");
	}

}
